### PR TITLE
Update addresses for Ropsten test network

### LINKED ISSUE #20: Incorrect addresses for Ropsten test network
The addresses declared in `src/constants.ts` for the Ropsten test network are incorrect and do not reflect the ones specified in [Compound docs](https://compound.finance/docs#networks) and in the [compound-config](https://github.com/compound-finance/compound-config/blob/master/networks/ropsten.json) repository.

### PR DESCRIPTION
**Pull request by SimoneStefani**
Change Ropsten test network addresses to reflect the ones specified in the [compound-config](https://github.com/compound-finance/compound-config/blob/master/networks/ropsten.json) repository.

Fixes #20

### CODE REVIEW

**Review by ajb413 — COMMENTED** [review]
Hello can you please add GovernorBravo? `0x087e98B40f988E0E1D1de476b2b8d2271Ac84B33`

**Comment by SimoneStefani** [comment]
Should be sorted. GovernorBravo is missing also from other networks constants but probably is wise to fix that in a separate PR.

The CI fails due to missing env var `MAINNET_PROVIDER_URL`.

**Comment by ajb413** [comment]
> Should be sorted. GovernorBravo is missing also from other networks constants but probably is wise to fix that in a separate PR.
> 
> The CI fails due to missing env var `MAINNET_PROVIDER_URL`.

Yes, I see that too. I also see this variable in the repository secrets, so I do not understand why this is failing. I will try to debug.

**Comment by SimoneStefani** [comment]
@ajb413 you may want to check [Improvements for public repository forks](https://github.blog/2020-08-03-github-actions-improvements-for-fork-and-pull-request-workflows/):

> In order to protect public repositories for malicious users we run all pull request workflows raised from repository forks with a read-only token and no access to secrets. This makes common workflows like labeling or commenting on pull requests very difficult.

> In order to solve this, we’ve added a new pull_request_target event, which behaves in an almost identical way to the pull_request event with the same set of filters and payload. However, instead of running against the workflow and code from the merge commit, the event runs against the workflow and code from the base of the pull request. This means the workflow is running from a trusted source and is given access to a read/write token as well as secrets enabling the maintainer to safely comment on or label a pull request.

**Comment by ajb413** [comment]
@SimoneStefani Ah ok great. This is helpful. I am new to actions. I can change to `pull_request_target` in build.yml of master. Then you can pull master and try again. Sound good?

**Comment by SimoneStefani** [comment]
@ajb413 Should be all good now

**Pull request merged**
